dependencies:
  - jupyter
  - matplotlib
  - numpy
  - psycopg2
  - pylint
  - pip
  - pytest
  - pip:
    - transformers
    - torch
    - gTTS
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-api-python-client
    - PyPDF2
    - python-docx
    - datasets
    - accelerate
    - sentencepiece
    - playwright
    - pytest-playwright
    - pytest-asyncio
